# Generated by Django 5.1.2 on 2024-10-23 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField(default=100)),
                ('hunger', models.IntegerField(default=0)),
                ('happiness', models.IntegerField(default=100)),
                ('last_fed', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_played', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
